In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'3.0.3'

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
data

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [5]:
data.shape

(9704, 11)

In [6]:
data.shape[0]

9704

In [7]:
data.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

In [9]:
data.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [11]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [13]:
(data.isnull().sum() > 0).sum()

np.int64(4)

In [25]:
data.groupby('origin')['fuel_efficiency_mpg'].agg(['min', 'max', 'mean'])

             min        max       mean
origin
Asia    6.886245  23.759123  14.973830
Europe  6.200971  25.967222  14.942532
USA     6.695483  24.971452  15.040204

In [31]:
data[data.origin == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [39]:
median_horsepower = data['horsepower'].median()
median_horsepower

np.float64(149.0)

In [44]:
mode_horsepower = data['horsepower'].mode()
mode_horsepower

0    152.0
Name: horsepower, dtype: float64

In [46]:
data['horsepower'].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ...
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [47]:
data['horsepower'].fillna(mode_horsepower).median()

np.float64(149.0)

In [61]:
X = data[data['origin'] == 'Asia'][['vehicle_weight', 'model_year']][:7]
X

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [63]:
XTX = X.T.dot(X)
XTX

                vehicle_weight    model_year
vehicle_weight    6.224833e+07  4.143122e+07
model_year        4.143122e+07  2.837334e+07

In [64]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [66]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [70]:
w = (XTX_inv @ X.T) @ y
w

0    0.013864
1    0.504907
dtype: float64

In [71]:
w.sum()

np.float64(0.5187709081074017)